kind: Namespace
apiVersion: v1
metadata:
  name: k8s4arch-hotels
  labels:
    name: k8s4arch-hotels
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels-deployment
  namespace: k8s4arch-hotels
  labels:
    app: k8s4arch-hotels
    frontend: react
    backend: python
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s4arch-hotels
      frontend: react
      backend: python
      version: v2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: k8s4arch-hotels
        frontend: react
        backend: python
        version: v2
    spec:
      containers:
      - name: k8s4arch-hotels
        image: ghcr.io/go-elevate/k8s4arch-hotels:monolith
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 2
          successThreshold: 3